from django.conf import settings


SMARTWATCH_GUNICORN_PORT = getattr(settings, 'SMARTWATCH_GUNICORN_PORT', 8000)
SMARTWATCH_GUNICORN_HOST = getattr(settings, 'SMARTWATCH_GUNICORN_HOST', '0.0.0.0')
SMARTWATCH_USE_GUNICORN = getattr(settings, 'SMARTWATCH_USE_GUNICORN', True)
SMARTWATCH_DAPHNE_PORT = getattr(settings, 'SMARTWATCH_DAPHNE_PORT', 8001)
SMARTWATCH_DAPHNE_HOST = getattr(settings, 'SMARTWATCH_DAPHNE_HOST', '0.0.0.0')
SMARTWATCH_USE_DAPHNE = getattr(settings, 'SMARTWATCH_USE_DAPHNE', True)

SMARTWATCH_COLLECT_STATIC = getattr(settings, 'SMARTWATCH_COLLECT_STATIC', True)
SMARTWATCH_MIGRATE = getattr(settings, 'SMARTWATCH_MIGRATE', True)