# Generated by Django 5.0.6 on 2024-05-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ras', '0003_auditupload_contractupload_delete_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditupload',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
