FROM python:3.10.12-slim
RUN apt update && apt install xpdf -y
RUN apt update && apt install -y g++

ENV PYTHONDONTWRITEBYTEapp=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt

WORKDIR /app
COPY . .

CMD ["python", "manage.py", "smartwatch"]