services:
    postgres:
        restart: always
        image: postgres:alpine
        env_file:
            - .env
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - .data/postgres:/var/lib/postgresql/data
    app:
        restart: always
        build: app
        env_file:
            - .env
        volumes:
            - ./app:/app
        extra_hosts:
            - "host.docker.internal:host-gateway"
    nginx:
        restart: always
        image: nginx:alpine
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ./.nginx:/etc/nginx/conf.d
            - ./app/staticfiles:/var/www/staticfiles
            - ./app/media:/var/www/media
