# Generated by Django 5.0.6 on 2024-05-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_logger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='log',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
