# Generated by Django 5.0.6 on 2024-05-16 05:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_logger', '0002_remove_log_timestamp_log_end_time_log_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='bogon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
