# Generated by Django 5.0.6 on 2024-05-18 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_logger', '0005_alter_log_end_time_alter_log_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='loc',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='log',
            name='is_new',
        ),
    ]
